import { Config, Colors } from "./model";
//方便外部获取
export class ConfigType{
	public static background_color:string="fui_background_olor"
	public static color:string="fui_color";
	
	//对应 keys
	public static keys:Array<string>=[
		"fui_background_olor",
		"fui_color",
		"fui_activeColor",
		"fui_primary",
		"fui_success",
		"fui_warning",
		"fui_error",
		"fui_info",
		"fui_gray",
		"fui_card_background_color",
	]
}
//设置配置
export const setConfig=(keys:Array<string>, config:Config,colors:Colors)=>{
	for(let i=0;i<keys.length;i++){
		config.set(keys[i],colors.get(keys[i]));
	}
}




//////////////////////////////////////////////////////////////////////////


//设置 Light 颜色
export const setLightColors=(colors:Colors)=>{
	colors.set(ConfigType.background_color,"#FFF");
	colors.set(ConfigType.color,"#F00");
}

//设置 Dark 颜色
export const setDarkColors=(colors:Colors)=>{
	colors.set(ConfigType.background_color,"#000");
	colors.set(ConfigType.color,"#00F");
}