import { ConfigType,setConfig,setDarkColors } from "./config.uts";
import { BaseTheme,Config, ThemeType,Colors, } from "./model.uts";

export class DarkConfig extends Config {
	constructor(){
		super()
		setConfig(ConfigType.keys,this, new DarkColors());
	}
}

export class DarkColors extends Colors{
	constructor(){
		super();
		setDarkColors(this);
	}
}


export class DarkTheme implements BaseTheme {
	constructor(){
	}
	public theme:ThemeType=ThemeType.DARK;
	public config:Config=new DarkConfig();
	
	init() {
		console.error("Theme:",this);
	}
	public getColor(c:string):string{
		const color= this.config.getString(c);
		if(color==null)return "";
		return color;
	}
}