import { ConfigType, setConfig,setLightColors } from "./config.uts";
import { BaseTheme, Colors, Config, ThemeType } from "./model.uts";

export class LightConfig extends Config {
	constructor(){
		super()
		setConfig(ConfigType.keys,this, new LightColors());
	}
}

export class LightColors extends Colors{
	constructor(){
		super();
		setLightColors(this);
	}
}

export class LightTheme implements BaseTheme {
	constructor(){
	}
	
	public theme:ThemeType=ThemeType.LIGHT;
	public config:Config = new LightConfig();
	
	init() {
		console.error("Theme:",this);
	}
	
	public getColor(c:string):string{
		const color= this.config.getString(c);
		if(color==null)return "";
		return color;
	}
}