import { BaseTheme, ThemeType } from "./model";
import { LightTheme } from "./light.uts"
import { DarkTheme } from "./dark.uts"

// 定义回调类型
export type IThemeDataCallback = (themeType : ThemeType) => void;

export class ThemeUtils {
	public theme : BaseTheme;
	private timer : number = 0;
	private themeCallback : IThemeDataCallback = (themeType : ThemeType) => { };
	//设置的皮肤类型
	private themeType : ThemeType = ThemeType.AUTO;

	constructor() {
		//这里要判断当前是什么皮肤,获取当前手机的皮肤信息
		this.theme = new DarkTheme();
		this.theme.init();
	}
	public setTheme(themeType : ThemeType) {
		this.themeType = themeType;
		if (themeType == ThemeType.AUTO) {
			this.updateTheme();
			this.runTask();
			return;
		}
		this.__setTheme(themeType);
	}
	private __setTheme(themeType : ThemeType) {
		let theme = this.getRealTheme().theme
		if (theme == themeType) return;
		if (themeType == ThemeType.LIGHT) {
			this.theme = new LightTheme();
		} else if (themeType == ThemeType.DARK) {
			this.theme = new DarkTheme();
		}
		this.theme.init();
		this.themeCallback(themeType);
	}

	public getRealTheme() : BaseTheme {
		return this.theme;
	}

	public getThemeType() : ThemeType {
		return this.themeType;
	}

	public setThemeChanged(callback : IThemeDataCallback) {
		this.themeCallback = callback;
	}

	private updateTheme() {
		let curDate = new Date();
		let h = curDate.getHours();
		let newThemeType : ThemeType = ThemeType.DARK;
		if (h >= 6 && h < 22) {
			newThemeType = ThemeType.LIGHT;
		}
		this.__setTheme(newThemeType);
	}
	//检查
	private runTask() {
		this.stopTask();
		this.timer = setTimeout(() => {
			this.updateTheme();
			console.error("TAG runTask,current themeType:", this.getRealTheme().theme);
			this.runTask();
		}, 3000);
	}
	//停止任务
	private stopTask() {
		if (this.timer > 0) {
			clearTimeout(this.timer);
		}
		this.timer = 0;
	}

}